title: <p align="center"> Peter Nguyen </p>
logo: /assets/img/grad_headshot.png
description:
  <p align="center">
  SF Bay Area
  <br> nguyenpeter@berkeley.edu
  <br> Resume | Handshake | GitHub
  </p>
theme: jekyll-theme-minimal
